language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install pytest pytest-cov codecov
  - pip install -e .

script:
  - pytest --cov .
  - python -m hsklcourses.__main__

after_success:
  - codecov